# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/notifications/notificationreqpb/notification_req.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/notifications/notificationreqpb/notification_req.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n=protos/notifications/notificationreqpb/notification_req.proto\"\x90\x01\n\x08NotifReq\x12\x13\n\x0b\x43ompanyUUID\x18\x01 \x01(\t\x12\x12\n\nDeviceUUID\x18\x02 \x01(\t\x12\x0e\n\x06\x41\x63tion\x18\x03 \x01(\t\x12\x0e\n\x06Intern\x18\x04 \x01(\x08\x12\r\n\x05\x45ntry\x18\x05 \x01(\x08\x12\x0b\n\x03Mid\x18\x06 \x01(\x08\x12\x0e\n\x06Senior\x18\x07 \x01(\x08\x12\x0f\n\x07Manager\x18\x08 \x01(\x08\x42\x13Z\x11notificationreqpbb\x06proto3')
)




_NOTIFREQ = _descriptor.Descriptor(
  name='NotifReq',
  full_name='NotifReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CompanyUUID', full_name='NotifReq.CompanyUUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DeviceUUID', full_name='NotifReq.DeviceUUID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Action', full_name='NotifReq.Action', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Intern', full_name='NotifReq.Intern', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Entry', full_name='NotifReq.Entry', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Mid', full_name='NotifReq.Mid', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Senior', full_name='NotifReq.Senior', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Manager', full_name='NotifReq.Manager', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=210,
)

DESCRIPTOR.message_types_by_name['NotifReq'] = _NOTIFREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotifReq = _reflection.GeneratedProtocolMessageType('NotifReq', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFREQ,
  __module__ = 'protos.notifications.notificationreqpb.notification_req_pb2'
  # @@protoc_insertion_point(class_scope:NotifReq)
  ))
_sym_db.RegisterMessage(NotifReq)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\021notificationreqpb'))
# @@protoc_insertion_point(module_scope)
