// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/notifications/notificationreq/notification_req.proto

package notificationreqpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotifReq struct {
	CompanyUUID          string   `protobuf:"bytes,1,opt,name=CompanyUUID,proto3" json:"CompanyUUID,omitempty"`
	DeviceUUID           string   `protobuf:"bytes,2,opt,name=DeviceUUID,proto3" json:"DeviceUUID,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=Action,proto3" json:"Action,omitempty"`
	Intern               bool     `protobuf:"varint,4,opt,name=Intern,proto3" json:"Intern,omitempty"`
	Entry                bool     `protobuf:"varint,5,opt,name=Entry,proto3" json:"Entry,omitempty"`
	Mid                  bool     `protobuf:"varint,6,opt,name=Mid,proto3" json:"Mid,omitempty"`
	Senior               bool     `protobuf:"varint,7,opt,name=Senior,proto3" json:"Senior,omitempty"`
	Manager              bool     `protobuf:"varint,8,opt,name=Manager,proto3" json:"Manager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifReq) Reset()         { *m = NotifReq{} }
func (m *NotifReq) String() string { return proto.CompactTextString(m) }
func (*NotifReq) ProtoMessage()    {}
func (*NotifReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5b22de4f7fd9cf9, []int{0}
}

func (m *NotifReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifReq.Unmarshal(m, b)
}
func (m *NotifReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifReq.Marshal(b, m, deterministic)
}
func (m *NotifReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifReq.Merge(m, src)
}
func (m *NotifReq) XXX_Size() int {
	return xxx_messageInfo_NotifReq.Size(m)
}
func (m *NotifReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifReq.DiscardUnknown(m)
}

var xxx_messageInfo_NotifReq proto.InternalMessageInfo

func (m *NotifReq) GetCompanyUUID() string {
	if m != nil {
		return m.CompanyUUID
	}
	return ""
}

func (m *NotifReq) GetDeviceUUID() string {
	if m != nil {
		return m.DeviceUUID
	}
	return ""
}

func (m *NotifReq) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *NotifReq) GetIntern() bool {
	if m != nil {
		return m.Intern
	}
	return false
}

func (m *NotifReq) GetEntry() bool {
	if m != nil {
		return m.Entry
	}
	return false
}

func (m *NotifReq) GetMid() bool {
	if m != nil {
		return m.Mid
	}
	return false
}

func (m *NotifReq) GetSenior() bool {
	if m != nil {
		return m.Senior
	}
	return false
}

func (m *NotifReq) GetManager() bool {
	if m != nil {
		return m.Manager
	}
	return false
}

func init() {
	proto.RegisterType((*NotifReq)(nil), "NotifReq")
}

func init() {
	proto.RegisterFile("pb/notifications/notificationreq/notification_req.proto", fileDescriptor_a5b22de4f7fd9cf9)
}

var fileDescriptor_a5b22de4f7fd9cf9 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x2f, 0x48, 0xd2, 0xcf,
	0xcb, 0x2f, 0xc9, 0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x46, 0xe1, 0x15, 0xa5,
	0x16, 0xa2, 0xf0, 0xe3, 0x8b, 0x52, 0x0b, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x95, 0xae, 0x31,
	0x72, 0x71, 0xf8, 0x81, 0xa4, 0x82, 0x52, 0x0b, 0x85, 0x14, 0xb8, 0xb8, 0x9d, 0xf3, 0x73, 0x0b,
	0x12, 0xf3, 0x2a, 0x43, 0x43, 0x3d, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x85,
	0x84, 0xe4, 0xb8, 0xb8, 0x5c, 0x52, 0xcb, 0x32, 0x93, 0x53, 0xc1, 0x0a, 0x98, 0xc0, 0x0a, 0x90,
	0x44, 0x84, 0xc4, 0xb8, 0xd8, 0x1c, 0x93, 0x41, 0x56, 0x48, 0x30, 0x83, 0xe5, 0xa0, 0x3c, 0x90,
	0xb8, 0x67, 0x5e, 0x49, 0x6a, 0x51, 0x9e, 0x04, 0x8b, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x94, 0x27,
	0x24, 0xc2, 0xc5, 0xea, 0x9a, 0x57, 0x52, 0x54, 0x29, 0xc1, 0x0a, 0x16, 0x86, 0x70, 0x84, 0x04,
	0xb8, 0x98, 0x7d, 0x33, 0x53, 0x24, 0xd8, 0xc0, 0x62, 0x20, 0x26, 0x48, 0x7f, 0x70, 0x6a, 0x5e,
	0x66, 0x7e, 0x91, 0x04, 0x3b, 0x44, 0x3f, 0x84, 0x27, 0x24, 0xc1, 0xc5, 0xee, 0x9b, 0x98, 0x97,
	0x98, 0x9e, 0x5a, 0x24, 0xc1, 0x01, 0x96, 0x80, 0x71, 0x9d, 0x84, 0xa3, 0x04, 0xd1, 0x82, 0xa0,
	0x20, 0x29, 0x89, 0x0d, 0xec, 0x69, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x8d, 0x0b,
	0xc9, 0x2f, 0x01, 0x00, 0x00,
}
