// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/locationpb/location.proto

package locationpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Location struct {
	Location             string   `protobuf:"bytes,1,opt,name=Location,proto3" json:"Location,omitempty"`
	CompanyName          string   `protobuf:"bytes,2,opt,name=CompanyName,proto3" json:"CompanyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_359cae6cb49e7157, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Location) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func init() {
	proto.RegisterType((*Location)(nil), "Location")
}

func init() {
	proto.RegisterFile("pb/locationpb/location.proto", fileDescriptor_359cae6cb49e7157)
}

var fileDescriptor_359cae6cb49e7157 = []byte{
	// 96 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x48, 0xd2, 0xcf,
	0xc9, 0x4f, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x43, 0x62, 0xea, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x2b,
	0x79, 0x70, 0x71, 0xf8, 0x40, 0x45, 0x84, 0xa4, 0x10, 0x6c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x84, 0x9c, 0x02, 0x17, 0xb7, 0x73, 0x7e, 0x6e, 0x41, 0x62, 0x5e, 0xa5, 0x5f, 0x62, 0x6e,
	0xaa, 0x04, 0x13, 0x58, 0x1a, 0x59, 0xc8, 0x89, 0x27, 0x8a, 0x0b, 0x61, 0x4d, 0x12, 0x1b, 0xd8,
	0x78, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0xac, 0x6f, 0x5a, 0x7e, 0x00, 0x00, 0x00,
}
