# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: companyrequestpb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='companyrequestpb.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x63ompanyrequestpb.proto\"%\n\x0e\x43ompanyRequest\x12\x13\n\x0b\x43ompanyName\x18\x01 \x01(\tB\x12Z\x10\x63ompanyrequestpbb\x06proto3')
)




_COMPANYREQUEST = _descriptor.Descriptor(
  name='CompanyRequest',
  full_name='CompanyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CompanyName', full_name='CompanyRequest.CompanyName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['CompanyRequest'] = _COMPANYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompanyRequest = _reflection.GeneratedProtocolMessageType('CompanyRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPANYREQUEST,
  __module__ = 'companyrequestpb_pb2'
  # @@protoc_insertion_point(class_scope:CompanyRequest)
  ))
_sym_db.RegisterMessage(CompanyRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\020companyrequestpb'))
# @@protoc_insertion_point(module_scope)
