# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/company/update_company_pb/update_company_details.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/company/update_company_pb/update_company_details.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n=protos/company/update_company_pb/update_company_details.proto\"\xbe\x01\n\x14UpdateCompanyDetails\x12\x13\n\x0b\x43ompanyUUID\x18\x01 \x01(\t\x12\x13\n\x0b\x43ompanyName\x18\x02 \x01(\t\x12\x16\n\x0e\x43ompanyWebsite\x18\x03 \x01(\t\x12\x12\n\nGreenHouse\x18\x04 \x01(\x08\x12\r\n\x05Lever\x18\x05 \x01(\x08\x12\r\n\x05Other\x18\x06 \x01(\x08\x12\x19\n\x11WantedDepartments\x18\x07 \x01(\t\x12\x17\n\x0fWantedLocations\x18\x08 \x01(\tB\x11Z\x0fupdatecompanypbb\x06proto3')
)




_UPDATECOMPANYDETAILS = _descriptor.Descriptor(
  name='UpdateCompanyDetails',
  full_name='UpdateCompanyDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CompanyUUID', full_name='UpdateCompanyDetails.CompanyUUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CompanyName', full_name='UpdateCompanyDetails.CompanyName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CompanyWebsite', full_name='UpdateCompanyDetails.CompanyWebsite', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GreenHouse', full_name='UpdateCompanyDetails.GreenHouse', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Lever', full_name='UpdateCompanyDetails.Lever', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Other', full_name='UpdateCompanyDetails.Other', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WantedDepartments', full_name='UpdateCompanyDetails.WantedDepartments', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WantedLocations', full_name='UpdateCompanyDetails.WantedLocations', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=256,
)

DESCRIPTOR.message_types_by_name['UpdateCompanyDetails'] = _UPDATECOMPANYDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateCompanyDetails = _reflection.GeneratedProtocolMessageType('UpdateCompanyDetails', (_message.Message,), dict(
  DESCRIPTOR = _UPDATECOMPANYDETAILS,
  __module__ = 'protos.company.update_company_pb.update_company_details_pb2'
  # @@protoc_insertion_point(class_scope:UpdateCompanyDetails)
  ))
_sym_db.RegisterMessage(UpdateCompanyDetails)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\017updatecompanypb'))
# @@protoc_insertion_point(module_scope)
