// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jobpb/job.proto

package jobpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	JobID                string   `protobuf:"bytes,1,opt,name=JobID,proto3" json:"JobID,omitempty"`
	Company_UUID         string   `protobuf:"bytes,2,opt,name=Company_UUID,json=CompanyUUID,proto3" json:"Company_UUID,omitempty"`
	JobLink              string   `protobuf:"bytes,3,opt,name=JobLink,proto3" json:"JobLink,omitempty"`
	DefaultLink          string   `protobuf:"bytes,4,opt,name=DefaultLink,proto3" json:"DefaultLink,omitempty"`
	ProvidedID           string   `protobuf:"bytes,5,opt,name=ProvidedID,proto3" json:"ProvidedID,omitempty"`
	Internship           bool     `protobuf:"varint,6,opt,name=Internship,proto3" json:"Internship,omitempty"`
	Entry                bool     `protobuf:"varint,7,opt,name=Entry,proto3" json:"Entry,omitempty"`
	Mid                  bool     `protobuf:"varint,8,opt,name=Mid,proto3" json:"Mid,omitempty"`
	Senior               bool     `protobuf:"varint,9,opt,name=Senior,proto3" json:"Senior,omitempty"`
	Manager              bool     `protobuf:"varint,10,opt,name=Manager,proto3" json:"Manager,omitempty"`
	Active               bool     `protobuf:"varint,11,opt,name=Active,proto3" json:"Active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_135a50213324ea52, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *Job) GetCompany_UUID() string {
	if m != nil {
		return m.Company_UUID
	}
	return ""
}

func (m *Job) GetJobLink() string {
	if m != nil {
		return m.JobLink
	}
	return ""
}

func (m *Job) GetDefaultLink() string {
	if m != nil {
		return m.DefaultLink
	}
	return ""
}

func (m *Job) GetProvidedID() string {
	if m != nil {
		return m.ProvidedID
	}
	return ""
}

func (m *Job) GetInternship() bool {
	if m != nil {
		return m.Internship
	}
	return false
}

func (m *Job) GetEntry() bool {
	if m != nil {
		return m.Entry
	}
	return false
}

func (m *Job) GetMid() bool {
	if m != nil {
		return m.Mid
	}
	return false
}

func (m *Job) GetSenior() bool {
	if m != nil {
		return m.Senior
	}
	return false
}

func (m *Job) GetManager() bool {
	if m != nil {
		return m.Manager
	}
	return false
}

func (m *Job) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func init() {
	proto.RegisterType((*Job)(nil), "job.Job")
}

func init() {
	proto.RegisterFile("jobpb/job.proto", fileDescriptor_135a50213324ea52)
}

var fileDescriptor_135a50213324ea52 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x40, 0xe9, 0xd6, 0xb6, 0xbb, 0x53, 0x41, 0x09, 0x22, 0x73, 0x92, 0xea, 0x69, 0x4f, 0x7a,
	0xf0, 0x0b, 0xd4, 0x7a, 0x68, 0x71, 0x41, 0x56, 0xf6, 0xe2, 0x45, 0x1a, 0x1b, 0x35, 0x55, 0x33,
	0x21, 0xc6, 0x85, 0xfd, 0x27, 0x3f, 0x52, 0x32, 0xd9, 0x42, 0x6f, 0x79, 0xef, 0x65, 0x60, 0x18,
	0x38, 0x1a, 0x48, 0x5a, 0x79, 0x35, 0x90, 0xbc, 0xb4, 0x8e, 0x3c, 0x89, 0x74, 0x20, 0x79, 0xf1,
	0x37, 0x83, 0xb4, 0x25, 0x29, 0x4e, 0x20, 0x6b, 0x49, 0x36, 0x35, 0x26, 0x55, 0xb2, 0x5c, 0xac,
	0x23, 0x88, 0x73, 0x38, 0xbc, 0xa3, 0x6f, 0xdb, 0x99, 0xdd, 0xcb, 0x66, 0xd3, 0xd4, 0x38, 0xe3,
	0x58, 0xee, 0x5d, 0x50, 0x02, 0xa1, 0x68, 0x49, 0x3e, 0x68, 0xf3, 0x89, 0x29, 0xd7, 0x11, 0x45,
	0x05, 0x65, 0xad, 0xde, 0xba, 0xdf, 0x2f, 0xcf, 0xf5, 0x20, 0xce, 0x4e, 0x94, 0x38, 0x03, 0x78,
	0x74, 0xb4, 0xd5, 0xbd, 0xea, 0x9b, 0x1a, 0x33, 0xfe, 0x30, 0x31, 0xa1, 0x37, 0xc6, 0x2b, 0x67,
	0x7e, 0x3e, 0xb4, 0xc5, 0xbc, 0x4a, 0x96, 0xf3, 0xf5, 0xc4, 0x84, 0xa5, 0xef, 0x8d, 0x77, 0x3b,
	0x2c, 0x38, 0x45, 0x10, 0xc7, 0x90, 0xae, 0x74, 0x8f, 0x73, 0x76, 0xe1, 0x29, 0x4e, 0x21, 0x7f,
	0x52, 0x46, 0x93, 0xc3, 0x05, 0xcb, 0x3d, 0x85, 0xdd, 0x57, 0x9d, 0xe9, 0xde, 0x95, 0x43, 0xe0,
	0x30, 0x62, 0x98, 0xb8, 0x79, 0xf5, 0x7a, 0xab, 0xb0, 0x8c, 0x13, 0x91, 0x6e, 0x8b, 0xe7, 0x8c,
	0xcf, 0x28, 0x73, 0xbe, 0xe1, 0xf5, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xa8, 0x3a, 0x31,
	0x56, 0x01, 0x00, 0x00,
}
