# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: company.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='company.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rcompany.proto\"K\n\x07\x43ompany\x12\x13\n\x0b\x43ompanyUUID\x18\x01 \x01(\t\x12\x13\n\x0b\x43ompanyName\x18\x02 \x01(\t\x12\x16\n\x0e\x43ompanyWebsite\x18\x03 \x01(\t\".\n\x0f\x43ompanyResponse\x12\x1b\n\tcompanies\x18\x01 \x03(\x0b\x32\x08.CompanyB\x0bZ\tcompanypbb\x06proto3')
)




_COMPANY = _descriptor.Descriptor(
  name='Company',
  full_name='Company',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CompanyUUID', full_name='Company.CompanyUUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CompanyName', full_name='Company.CompanyName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CompanyWebsite', full_name='Company.CompanyWebsite', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=92,
)


_COMPANYRESPONSE = _descriptor.Descriptor(
  name='CompanyResponse',
  full_name='CompanyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='companies', full_name='CompanyResponse.companies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=140,
)

_COMPANYRESPONSE.fields_by_name['companies'].message_type = _COMPANY
DESCRIPTOR.message_types_by_name['Company'] = _COMPANY
DESCRIPTOR.message_types_by_name['CompanyResponse'] = _COMPANYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Company = _reflection.GeneratedProtocolMessageType('Company', (_message.Message,), dict(
  DESCRIPTOR = _COMPANY,
  __module__ = 'company_pb2'
  # @@protoc_insertion_point(class_scope:Company)
  ))
_sym_db.RegisterMessage(Company)

CompanyResponse = _reflection.GeneratedProtocolMessageType('CompanyResponse', (_message.Message,), dict(
  DESCRIPTOR = _COMPANYRESPONSE,
  __module__ = 'company_pb2'
  # @@protoc_insertion_point(class_scope:CompanyResponse)
  ))
_sym_db.RegisterMessage(CompanyResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\tcompanypb'))
# @@protoc_insertion_point(module_scope)
